### PR TITLE
Fix multiple syntax issues in wml, wmk, and ipp

### PR DESCRIPTION
**Pull request by xtaran**
Contains fixes for #10 and #12, one commit per fix.

Feel free to cherry-pick single commits out of this pull request in case you don't want to merge all three commits.

### CODE REVIEW

**Comment by xtaran** [comment]
Hrm, I think I see what causes the CI failures. Will push a fix for that soon. Interestingly it didn't bail out when building my site. :-)

**Comment by shlomif** [comment]
@xtaran : hi! Thanks, but note that I fixed an issue in somewhat different way and now there is a conflict. Please fix the Pull-req. Thanks!

**Comment by xtaran** [comment]
> @xtaran : hi! Thanks, but note that I fixed an issue in somewhat different way and now there is a conflict.

Saw it, thanks.

> Please fix the Pull-req. Thanks!

Done.

**Comment by xtaran** [comment]
Hrm, this time I'm not sure what broke. Definitely less than last time, but for me locally the test suite exits immediately, so I can't really test locally:

```
[…]te-meta-language/src → make test
Running tests...
Test project /home/abe/wml/website-meta-language/src
    Start 1: wml_tests
1/1 Test #1: wml_tests ........................***Failed    0.71 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.72 sec

The following tests FAILED:
          1 - wml_tests (Failed)
Errors while running CTest
make: *** [Makefile:120: test] Error 8
```

Any hints on either the failing Travis CI or on my local issue? If so, I'm happy to further debug the issue.

**Comment by xtaran** [comment]
Ah, AppVeyor is more clear. Will tidy up that one long line which even got longer.

**Comment by xtaran** [comment]
(It's IMHO still dicussable if it's more readable that way. :-)

**Comment by xtaran** [comment]
Ah, you've fixed it yourself. Thanks! Hence closing.

**Comment by shlomif** [comment]
Hi!

I fixed the perltidy tests in a separate commit. Thanks!

**Pull request closed without merging**
