### PR TITLE
refactor & correct typos in wml::fmt::text

### PR DESCRIPTION
**Pull request by shlomif**
Hi @xtaran !

Please review this pull-req. I'm not using wml::fmt::text a lot and would rather not break it.

### CODE REVIEW

**Comment by xtaran** [comment]
Hmmm, as far as I can see, we don't really have a test for that. Since I don't remember to use that anywhere, I'd write a test (likely in the master branch) and see if it also passes in the feature branch.

**Comment by shlomif** [comment]
On Mon, 31 Aug 2020 08:00:12 -0700
Axel Beckert <notifications@github.com> wrote:

> Hmmm, as far as I can see, we don't really have a test for that. Since I
> don't remember to use that anywhere, I'd write a test (likely in the master
> branch) and see if it also passes in the feature branch.
> 

Thanks, @xtaran !


-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/facts/Taylor-Swift/

Always reach for the stars! Because even if you miss… You’ll be miles away
from me with your motivational bullshit.
    — https://is.gd/PuH02m

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by xtaran** [comment]
Sigh, seems as we've crossed each other in fixing the test failure due to a missing txt2html.

**Comment by xtaran** [comment]
Wanted to fix this in the test itself before adding it to `.travis.yml` and `.appveyor.yml` to make sure the check in the test itself works.

**Comment by xtaran** [comment]
Testing this now via branch at https://github.com/thewml/website-meta-language/tree/skip-wml-fmt-text-if-txt2html-not-installed

**Comment by xtaran** [comment]
Thanks, for some reason I was not able to get `perltidy` to emit these errors, even with the included `.perltidyrc`.

**Review by xtaran — COMMENTED** [review]
Passes the same test as the old code, hence that's an ok.

**Pull request merged**
